package com.example.submissionjatpackcompose.model

import com.example.submissionjatpackcompose.R

object PetDataSource {
    val dummyPet = listOf(
        DataPet(1, R.drawable.anjing1,"Puddel","Anjing","Pudel adalah anjing dari kelompok non-sporting atau utility yang berasal dari Prancis. Ada beberapa jenis pudel, misalnya: pudel standar, miniatur dan mainan. Pudel-pudel yang terkenal adalah Georgette dari Oliver & Company, Cleo dari Clifford the Big Red Dog, Barbara Ann dari Good Boy!, Fifi dari \"Open Season 2\" dan \"Open Season 3\" dan sebagainya. Pudel atau biasa dikenal sebagai Poodle, adalah anjing yang berbulu keriting. Anjing ini memiliki beberapa macam warna, seperti putih, coklat, dan hitam. Pudel biasa di pangkas rambutnya dan disisakan kakinya, atas kepalanya, Dekat lehernya dan juga bagian pinggangnya. Anjing pudel betina memiliki ekor yang pendek, sementara yang jantan memiliki ekor yang panjang."),
        DataPet(2, R.drawable.anjing2,"German Shepherd","Anjing","Anjing Gembala Jerman (bahasa Inggris: German Shepherd Dog; bahasa Jerman:(Deutscher Schäferhund) adalah salah satu ras murni anjing yang populer. Ukurannya besar, dikenal cerdas namun penurut. Anjing ini relatif tidak memiliki variasi warna, yaitu coklat dengan variasi hitam. Dahulu, anjing Gembala Jerman sering digunakan untuk menggembalakan domba."),
        DataPet(3, R.drawable.anjing3,"Beagle","Anjing","Beagle, atau biasa dikenal dengan Anjing Pemburu adalah ras anjing terkecil dari famili anjing pemburu yang aslinya berasal dari Inggris. Beagle diklasifikasikan menjadi empat jenis, yaitu: Beagle berukuran sedang, Beagle kerdil atau kecil, Beagle rubah, dan Beagle terrier (berbulu kasar).[2] Dalam sejarahnya, anjing ini sering dimanfaatkan dalam berburu kelinci karena memiliki penciuman yang tajam walaupun pergerakkannya tidak terlalu cepat.[2] Pada tahun 1923, populasi Beagle hampir mengalami kepunahan di Inggris karena banyak masyarakat di sana yang tidak lagi menyukai berburu bersama Beagle"),
        DataPet(4, R.drawable.anjing4,"Golden Retriever","Anjing","Golden Retriever adalah anjing trah yang mulanya dibiakkan sebagai anjing pemburu untuk mengambil burung hasil buruan yang sudah ditembak. Anjing trah ini termasuk jenis Retriever (pengambil) yang menemukan atau mengambilkan burung air atau unggas liar untuk pemburu. Bulu mereka keemasan (golden) di bawah sinar matahari sehingga disebut Golden Retriever."),
        DataPet(5, R.drawable.burung1,"Kacer","Burung","Kacer adalah burung pengicau kecil yang sebelumnya dikelompokkan sebagai anggota keluarga Turdidae (murai), tetapi kini dianggap sebaagi anggota Muscicapidae. Burung ini berwarna hitam dan putih dengan ekor yang panjang. Ekornya terangkat ke atas jika mereka sedang mencari makanan di tanah atau kadang ketika sedang bertengger. Burung ini banyak ditemukan di daerah Asia Selatan dan Asia tenggara. Di Indonesia burung ini mulai langka karena penangkapan yang berlebihan untuk dipelihara."),
        DataPet(6, R.drawable.burung2,"Gereja","Burung","Burung gereja disebut juga burung pingai adalah jenis burung pipit kecil yang berasal dari keluarga Passeridae. Burung gereja mendiami kota-kota dalam jumlah yang sangat besar.Sparrow merupakan burung yang jinak dari semua burung liar dan memiliki tingkat adaptasi yang tinggi terhadap lingkungannya seperti perubahan kondisi cuaca, ketersediaan pakan maupun predator. Oleh karena itu, burung gereja dianggap sebagai burung yang tidak takut didekat manusia atau disebut human dominated ecosystem."),
        DataPet(7, R.drawable.burung3,"Candet Kembang","Burung","Candet adalah spesies burung dari keluarga Laniidae, dari genus Lanius. Burung ini merupakan jenis burung pemakan belalang, kumbang, tonggeret, serangga besa dan memiliki habitat di daerah terbuka, padang rumput, perkebunan, tegalan. tersebar sampai ketinggian 1.600 m dpl."),
        DataPet(8, R.drawable.kucing1,"Abyssinian","Kucing","Kucing abisinia adalah salah satu ras kucing berbulu pendek tertua yang pernah diketahui. Abisinia menyerupai lukisan dan patung yang berasal dari zaman Mesir Kuno. Perdagangan ras kucing ini dilarang oleh bangsa Mesir. Selain itu, bangsa Mesir juga mendirikan kuil khusus untuk memuja abisinia. Mumi abisinia banyak ditemukan pada makam-makam bangsa Mesir Kuno. Pada saat bangsa Romawi menguasai Mesir, abisinia pernah dibawa ke Inggris dengan tujuan melindungi ladang gandum dari tikus"),
        DataPet(9, R.drawable.kucing2,"Tiffanie","Kucing","Tiffanie adalah salah satu ras kucing domestik terbaru keturunan burmilla yang berasal dari Australia. Ras kucing ini merupakan hasil persilangan dari kucing burma dan kucing persia chinchilla. Pada dasarnya, tiffanie australia adalah kucing ras bulu setengah panjang burmilla. Tiffanie australia pertama kali diakui oleh Waratah State Cat Alliance pada tahun 1999"),
        DataPet(10, R.drawable.kucing3,"Turkish Van","Kucing","Van turki (bahasa Inggris: Turkish Van; bahasa Turki: Van kedisi) adalah salah satu ras kucing alami yang berasal dari Turki. Van turki pertama kali dikembangkan di Inggris. Van turki dijuluki sebagai \"kucing perenang\", karena van turki sangat suka dengan air. Ras kucing ini diberinama \"Van\" karena kucing ini memiliki warna putih dibagian badan, dan warna lain dibagian kepala dan ekor"),
        DataPet(11, R.drawable.kucing4,"Siberia","Kucing","Kucing siberia (atau kucing bulu setengah panjang moskwa) adalah salah satu ras kucing domestik alami yang berasal dari Siberia, Rusia.[2] Kucing siberia memiliki nama lengkap kucing hutan siberia. Beberapa organisasi pendaftaran kucing menyebut kucing siberia titik warna dengan sebutan neva masquerade"),
        DataPet(12, R.drawable.kucing5,"Scottish Fold","Kucing","salah satu ras kucing alami yang berasal dari Skotlandia. Ciri khas dan keunikannya adalah terdapat pada telingnya yang melipat, sehingga ras ini disebut dengan kucing berwajah burung hantu atau kucing coupari. Namun, beberapa kucing telinga lipat skotlandia ada yang lahir dengan telinga yang tidak terlipat, yaitu telinga yang tegak dan meruncing seperti kucing biasanya"),
        DataPet(13, R.drawable.marmut,"Alpacas","Marmut","Marmot adalah sejenis hewan pengerat yang tergolong familia Sciuridae (bajing) dengan genus Marmota. Marmot umumnya hidup di daerah pegunungan, seperti Alpen atau Pirenia di Eropa, Pegunungan Rocky atau Sierra Nevada di Amerika Serikat, dan Kanada bagian utara. Marmot umumnya membuat sarang di dalam tanah dan melakukan hibernasi selama musim dingin. Kebanyakan marmot tergolong hewan sosial; marmot berkomunikasi satu sama lain dengan siulan nyaring, terutama jika merasa ada bahaya.")


    )
}